[platformio]
src_dir = benchmarks
default_envs = r3-sort, r4-sort
extra_configs =
  boards.ini
  benchmarks.ini


; Regular sort algorithms
[env:r3-sort]
extends = r3, sort

[env:r4-sort]
extends = r4, sort


; LLM Sort algorithms
[env:r3-llm-sort]
extends = r3, llm-sort

[env:r4-llm-sort]
extends = r4, llm-sort


; LLM Sort (floating) algorithms
[env:r3-llm-sort-floating]
extends = r3, llm-sort-floating

[env:r4-llm-sort-floating]
extends = r4, llm-sort-floating


; Crypto algorithms
[env:r3-crypto]
extends = r3, crypto

[env:r4-crypto]
extends = r4, crypto


; Misc algorithms
[env:r3-misc]
extends = r3, misc

[env:r4-misc]
extends = r4, misc