[platformio]
src_dir = benchmarks
default_envs = r3-sort-measure, r4-sort-measure
extra_configs =
  pio-config/01-boards.ini
  pio-config/02-benchmarks.ini
  pio-config/03-buildmodes.ini

; =========== Experiment: Sort ===========
[env:r3-sort-debug]
extends = r3, sort, debug

[env:r4-sort-debug]
extends = r4, sort, debug

[env:r3-sort-measure]
extends = r3, sort, measure

[env:r4-sort-measure]
extends = r4, sort, measure


; =========== Experiment: LLM Sort ===========
[env:r3-llm-sort-debug]
extends = r3, llm-sort, debug

[env:r4-llm-sort-debug]
extends = r4, llm-sort, debug

[env:r3-llm-sort-measure]
extends = r3, llm-sort, measure

[env:r4-llm-sort-measure]
extends = r4, llm-sort, measure


; =========== Experiment: LLM Sort Floating ===========
[env:r3-llm-sort-floating-debug]
extends = r3, llm-sort-floating, debug

[env:r4-llm-sort-floating-debug]
extends = r4, llm-sort-floating, debug

[env:r3-llm-sort-floating-measure]
extends = r3, llm-sort-floating, measure

[env:r4-llm-sort-floating-measure]
extends = r4, llm-sort-floating, measure


; =========== Experiment: Crypto ===========
[env:r3-crypto-debug]
extends = r3, crypto, debug

[env:r4-crypto-debug]
extends = r4, crypto, debug

[env:r3-crypto-measure]
extends = r3, crypto, measure

[env:r4-crypto-measure]
extends = r4, crypto, measure


; =========== Experiment: Misc ===========
[env:r3-misc-debug]
extends = r3, misc, debug

[env:r4-misc-debug]
extends = r4, misc, debug

[env:r3-misc-measure]
extends = r3, misc, measure

[env:r4-misc-measure]
extends = r4, misc, measure


; =========== Experiment: Instruction ===========
[env:r3-instruction-debug]
extends = r3, instruction, debug

[env:r4-instruction-debug]
extends = r4, instruction, debug

[env:r3-instruction-measure]
extends = r3, instruction, measure

[env:r4-instruction-measure]
extends = r4, instruction, measure

